site_name: Pluggedspace Docs
site_description: Official documentation for Pluggedspace's unified tools.
site_url: https://docs.pluggedspace.org

theme:
  name: material
  logo: images/Pluggedspace.png
  favicon: images/favicon.ico
  palette:
    - scheme: default
      primary: black
      accent: blue

  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pluggedspace_io
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/pluggedspace
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/pluggedspace
    - icon: fontawesome/brands/github
      link: https://github.com/pluggedspace
    - icon: fontawesome/solid/envelope
      link: mailto:contact@pluggedspace.org
    - icon: fontawesome/solid/globe
      link: https://pluggedspace.org
    - icon: fontawesome/solid/book
      link: https://blog.pluggedspace.org
  generator: false

nav:
  - Home: index.md
  - Atlas:
      - Overview: data/index.md
  - Job Autobot:
      - Overview: models/job/index.md
  
